# Generated by Django 5.1.4 on 2025-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vokabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('german', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('turkish', models.CharField(max_length=100)),
            ],
        ),
    ]
