# Generated by Django 5.1.4 on 2025-01-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vokabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingularPlural',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('singular', models.CharField(max_length=100)),
                ('plural', models.CharField(max_length=100)),
                ('vokabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singular_plural', to='Vokabel.vokabel')),
            ],
        ),
    ]
