# Generated by Django 5.1.4 on 2025-01-14 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user-photo.png', null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='GamesRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
