# Generated by Django 5.1.4 on 2025-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_profile_image_gamesrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesrecords',
            name='game_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
