# Generated by Django 5.1.4 on 2025-01-18 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gamesrecords_game_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vokabel_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('singular_plural_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('artikel_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('adjektiv_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('adjektiv_deklination_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('verb_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('present_verb_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('past_verb_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('partizip_II_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Total scores must be 0 or greater.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
